trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0
  inputs:
    GitRepoUrl: 'https://Git@dev.azure.com:v3/jhenry0421/Project2-TelecomPortal/_git/Project2-TelecomPortal.git'
